import "./globals.css";
import { Urbanist } from "next/font/google";
import Link from "next/link";
import { Metadata } from "next";
import Navbar from "./reusableComponents/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const urbanist = Urbanist({
  subsets: ["latin"],
  weight: ["200", "400", "600", "800"],
  variable: "--font-urbanist",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${urbanist.variable} font-urbanist bg-slate-800 text-gray-100`}>
      <Navbar/>
        {children}
      </body>
    </html>
  );
}
